server:
  port: 8081

spring:
  application:
    name: auth-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: "devloger-super-secret-key-1234567890-jwt-secure-key!!" # 256비트 이상
  expiration: 3600000 # 1시간 (ms 기준)