name: Deploy auth-service to GKE

on:
  push:
    paths:
      - 'auth-service/**'
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew :auth-service:bootJar

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1

      - name: Authenticate Docker to Artifact Registry
        run: |
          gcloud auth configure-docker asia-northeast3-docker.pkg.dev --quiet

      - name: Docker Build & Push
        run: |
          IMAGE=asia-northeast3-docker.pkg.dev/${{ secrets.PROJECT_ID }}/docker-repo/auth-service:$GITHUB_SHA
          docker build -t $IMAGE -f auth-service/Dockerfile .
          docker push $IMAGE

      - name: Connect to GKE
        run: |
          gcloud container clusters get-credentials ${{ secrets.CLUSTER_NAME }} \
            --region=${{ secrets.REGION }} --project=${{ secrets.PROJECT_ID }}

      - name: Deploy to GKE
        env:
          IMAGE: asia-northeast3-docker.pkg.dev/${{ secrets.PROJECT_ID }}/docker-repo/auth-service:${{ github.sha }}
        run: |
          kubectl set image deployment/auth-service auth-service=$IMAGE
