name: Deploy auth-service to GKE

on:
  push:
    paths:
      - 'auth-service/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      USE_GKE_GCLOUD_AUTH_PLUGIN: "True"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install gcloud + kubectl
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          install_components: 'kubectl'
          project_id: ${{ secrets.PROJECT_ID }}
          credentials: ${{ secrets.GCP_CREDENTIALS }}

      - name: Activate service account explicitly
        run: |
          echo "${{ secrets.GCP_CREDENTIALS_BASE64 }}" | base64 -d > /tmp/key.json
          gcloud auth activate-service-account --key-file=/tmp/key.json
          gcloud config set project ${{ secrets.PROJECT_ID }}
          gcloud config set compute/region ${{ secrets.REGION }}
          gcloud config set compute/zone ${{ secrets.ZONE }}


      - name: Authenticate Docker to Artifact Registry
        run: gcloud auth configure-docker asia-northeast3-docker.pkg.dev --quiet

      - name: Build & Push Docker Image
        run: |
          IMAGE=asia-northeast3-docker.pkg.dev/${{ secrets.PROJECT_ID }}/docker-repo/auth-service:$GITHUB_SHA
          docker build -t $IMAGE -f auth-service/Dockerfile .
          docker push $IMAGE

      - name: Connect to GKE
        run: |
          gcloud container clusters get-credentials ${{ secrets.CLUSTER_NAME }} \
            --region=${{ secrets.REGION }} --project=${{ secrets.PROJECT_ID }}

      - name: Deploy to GKE
        run: |
          IMAGE=asia-northeast3-docker.pkg.dev/${{ secrets.PROJECT_ID }}/docker-repo/auth-service:$GITHUB_SHA
          kubectl set image deployment/auth-service auth-service=$IMAGE
